### ISSUE TITLE
🕵️ Kontrola REST endpointů

### ISSUE THREAD

**Issue by ThomasBig** [JirkaVrbka/Rust-StockTradingSimulator#12]
- [ ] Zdokumentovat funkční end pointy - nejsem si jistý, jak README.md je up to date. 
- [ ] Zdokumentovat nefunkční end pointy - jsou všechny v api OK?
- [ ] Zdokumentovat chybějící end pointy - Michal nestihl dodělat kód, jsou tam založené proměnné ale už se s nimi nic dalšího neprovádí.
- [ ] Vypsat nové úkoly do #3

Dokumentace může být lehce provedena pomocí open sourceru https://swagger.io/
![image](https://user-images.githubusercontent.com/11876105/145789147-89abdc0a-2cec-4dd3-9ee8-b9099cd228ff.png)

**Comment by lukegryga** [comment]
Snažil jsem se přijít na to jak z kódu jednoduše generovat OpenAPI v rustu. Po 3 hodinách průzkumu jsem narazil na jediné funkční řešení pomocí [peperclip](https://crates.io/crates/paperclip). 

- Ten funguje tak, že vytvoří wrapper kolem actix::web (jsou tam pak kompatibilní problémy)
- Nepodporuje routování endpontů pomocí atributů, takže by se všechno routování muselo dělat následovně:
```rust
.service(web::resource("/stonkers")
                .route(web::get().to(get_stonkers)))
```
- Používá vlastní wrapper Json (místo HttpResponse), je to obecně problematické.

Zhodnotil jsem že automatické generování OpenAPI nám za ty komplikace nestojí.
