### ISSUE TITLE
☁️ Hosting na cloudu

### ISSUE THREAD

**Issue by ThomasBig** [JirkaVrbka/Rust-StockTradingSimulator#5]
Zjistit, jaký cloud by byl schopný nám hostovat projekt 🦀. Setupnout server pro celý svět na vidění 📦 ✈️ 🌍 . Čím dříve to uděláme, tím méně problémů bude v budoucnu 👍.

Dobrý start
* https://www.fi.muni.cz/tech/unix/web.html.cs
* https://www.fi.muni.cz/tech/unix/html-pages.html.cs
* https://www.fi.muni.cz/tech/win/msdnaa.html.cs (Azure 100$)
* Heroku a jiné zdarma cloudové platformy. [Tutoriál](https://dev.to/gruberb/web-programming-in-rust-02x-deploy-your-first-app-1k05).

**Comment by lukegryga** [comment]
Netušil jsem, jak moc Azure stojí. Zbývá mi kredit asi na 2 týdny běhu naší aplikace (25$), tak do deploynu, až to budeme prezetovat. Vyzkoušené to mám.
